"""Candidate-intake automerge eligibility guard.

The admission gate for the ``automerge:candidate-intake`` lane. A candidate-intake
PR stages non-canonical candidate records under ``maintenance/candidates/*.json``.
Those records are produced and written by the unified resolver's durable ingress
(``vendor_resolution.CatalogQueueIngress`` — the single canonical writer), never
by this guard. Merging such a PR does not write catalogue truth (``data/**``) and
does not decide promotion — promotion still flows through the independent
quorum/promotion path.

This guard makes an auto-merge admission decision by requiring that the PR:

1. touches ONLY single-level ``maintenance/candidates/*.json`` files (path
   confinement, via the shared ``automerge_lanes.is_candidate_intake_path``);
2. carries no canonical (``data/**``) or generated (``indexes/``, ``dist/``,
   ``openva-pack.json``) drift; and
3. has a schema-valid candidate record for every added/modified file.

Reproducibility of the committed ``eligibility_state`` against the canonical
resolver's evaluation is intentionally NOT checked here: re-deriving the
resolver's per-origin eligibility in this side module would be a second evaluator.
That admission check belongs WITH the consuming agent-automerge candidate-intake
job (the external GitHub-App boundary; see ``docs/candidate-intake.md``), where it
can call the resolver's own evaluation path. Until that job exists the lane is
``execution_wired: false`` and nothing auto-merges.

Deletions within the store (e.g. cross-origin dedup removals) are path-confined
and permitted; the guard is not append-only. Fails closed: any reason ⇒ ineligible.

Operational metadata only. Not legal, compliance, procurement, security, KYC,
AML, audit, or vendor-risk advice.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

from tools.openva import candidate_record as cr
from tools.openva.automerge_lanes import (
    AUTOMERGE_CANDIDATE_INTAKE,
    is_candidate_intake_path,
    is_generated_path,
    is_machine_canonical_path,
)
from tools.openva.indexes import ROOT

CANDIDATE_INTAKE_LABEL = "candidate-intake"


@dataclass(frozen=True)
class CandidateIntakeResult:
    eligible: bool
    reasons: tuple[str, ...]


def check_candidate_intake(
    changed_paths: list[str], labels: list[str], root: Path = ROOT
) -> CandidateIntakeResult:
    reasons: list[str] = []
    clean_labels = {label.strip() for label in labels if label.strip()}
    for required in (CANDIDATE_INTAKE_LABEL, AUTOMERGE_CANDIDATE_INTAKE):
        if required not in clean_labels:
            reasons.append(f"missing_label:{required}")

    paths = [path.strip() for path in changed_paths if path.strip()]
    if not paths:
        return CandidateIntakeResult(False, ("no_changed_paths",))

    for path in paths:
        # (1) path confinement — shared predicate with the lane checker.
        if not is_candidate_intake_path(path):
            reasons.append(f"disallowed_path:{path}")
            continue
        # (2) explicit no canonical/generated drift. Non-load-bearing after (1)
        # (the candidate-intake path space is disjoint from canonical/generated by
        # construction); kept as independent defence-in-depth.
        if is_machine_canonical_path(path) or is_generated_path(path):
            reasons.append(f"canonical_or_generated_drift:{path}")
            continue

        full = root / path
        if not full.exists():
            # A deletion within the store (cross-origin dedup removal): path-confined
            # and permitted; nothing on disk to schema-check. The caller must check
            # out the PR head so an added file always exists on disk.
            continue

        # (3) schema validity.
        try:
            record = json.loads(full.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            reasons.append(f"{path}:invalid_json:{type(exc).__name__}")
            continue
        if not isinstance(record, dict):
            reasons.append(f"{path}:not_a_candidate_record")
            continue
        reasons.extend(f"{path}:{error}" for error in cr.validate_candidate(record))

    return CandidateIntakeResult(not reasons, tuple(reasons))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="openva-candidate-intake-guard")
    parser.add_argument("--paths-file", required=True)
    parser.add_argument("--labels", default="")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args(argv)

    paths = Path(args.paths_file).read_text(encoding="utf-8").splitlines()
    result = check_candidate_intake(paths, args.labels.split(","), root=args.root)
    print(f"eligible={str(result.eligible).lower()}")
    for reason in result.reasons:
        print(f"reason={reason}")
    return 0 if result.eligible else 1


if __name__ == "__main__":
    raise SystemExit(main())
