from __future__ import annotations

import argparse
import socket
import urllib.error
import urllib.request
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from tools.openva.hash import sha256_bytes, sha256_normalized_text
from tools.openva.indexes import ROOT, records_for
from tools.openva.url_safety import validate_url_safety

USER_AGENT = "open-vendor-assurance-observer/0.1 (+metadata-only; public sources only)"
MAX_BYTES = 2_000_000
TIMEOUT_SECONDS = 20
PILOT_CONFIG = ROOT / "config" / "observation-pilot.yaml"

BOT_PROTECTED_STATUS_CODES = {401, 403, 407, 429}

BLOCKED_HINTS = (
    "login",
    "sign in",
    "signin",
    "access denied",
    "forbidden",
    "captcha",
    "verify you are human",
    "customer portal",
    "trust portal",
    "request access",
    "cloudflare",
    "checking your browser",
    "attention required",
)


def now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def safe_observation_id(source_id: str, observed_at: str) -> str:
    date = observed_at[:10]
    return f"{source_id}-{date}"


def load_pilot_source_ids() -> set[str]:
    if not PILOT_CONFIG.exists():
        raise FileNotFoundError(f"{PILOT_CONFIG.relative_to(ROOT)} is missing")
    config = yaml.safe_load(PILOT_CONFIG.read_text(encoding="utf-8")) or {}
    source_ids = config.get("sources", [])
    if not isinstance(source_ids, list) or not all(isinstance(item, str) for item in source_ids):
        raise ValueError("config/observation-pilot.yaml: sources must be a list of source_id strings")
    return set(source_ids)


def select_sources(*, pilot_only: bool) -> list[dict[str, Any]]:
    sources = [source for source in records_for("source") if not source["_openva_path"].startswith("examples/")]
    if not pilot_only:
        return sources

    pilot_ids = load_pilot_source_ids()
    available_ids = {source["source_id"] for source in sources}
    missing_ids = sorted(pilot_ids - available_ids)
    if missing_ids:
        missing = ", ".join(missing_ids)
        raise ValueError(f"config/observation-pilot.yaml references unknown source_id(s): {missing}")
    return [source for source in sources if source["source_id"] in pilot_ids]


def fetch_public(url: str) -> tuple[str, int | None, str | None, bytes]:
    if validate_url_safety(url):
        return "quarantined", None, None, b""

    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT_SECONDS) as response:
            status = int(response.status)
            final_url = response.geturl()
            if validate_url_safety(final_url):
                return "quarantined", status, final_url, b""
            data = response.read(MAX_BYTES + 1)
            if len(data) > MAX_BYTES:
                return "size_limited", status, final_url, b""
            return "ok", status, final_url, data
    except urllib.error.HTTPError as error:
        status = int(error.code)
        if status in BOT_PROTECTED_STATUS_CODES:
            return "bot_protected", status, url, b""
        return "fetch_failed", status, url, b""
    except (urllib.error.URLError, TimeoutError, socket.timeout):
        return "fetch_failed", None, url, b""


def looks_blocked(data: bytes) -> bool:
    text = data[:50_000].decode("utf-8", errors="ignore").lower()
    return any(hint in text for hint in BLOCKED_HINTS)


def observation_for_source(source: dict[str, Any]) -> dict[str, Any]:
    observed_at = now_iso()
    source_id = source["source_id"]
    result, http_status, final_url, data = fetch_public(source["source_url"])

    if result == "ok" and looks_blocked(data):
        result = "bot_protected"
        data = b""

    if result == "ok":
        raw_hash = sha256_bytes(data)
        text_hash = sha256_normalized_text(data)
    else:
        raw_hash = "sha256:TBD"
        text_hash = "sha256:TBD"

    return {
        "schema_version": "0.1.0",
        "observation_id": safe_observation_id(source_id, observed_at),
        "vendor_id": source["vendor_id"],
        "source_id": source_id,
        "artifact_id": None,
        "observed_at": observed_at,
        "result": result,
        "http_status": http_status,
        "final_url": final_url,
        "access_class": source["access_class"],
        "hashes": {
            "raw_sha256": raw_hash,
            "normalized_text_sha256": text_hash,
            "etag": None,
            "last_modified": None,
        },
        "storage": {
            "raw_document_stored": False,
            "extracted_text_stored": False,
            "screenshot_stored": False,
        },
        "notes": "Generated by OpenVA public-source observation tooling. Raw content not stored.",
    }


def write_observation(observation: dict[str, Any]) -> Path:
    vendor_id = observation["vendor_id"]
    observation_id = observation["observation_id"]
    path = ROOT / "data" / "vendors" / vendor_id / "observations" / f"{observation_id}.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(observation, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return path


def observe_sources(dry_run: bool, *, pilot_only: bool) -> int:
    created = []
    for source in select_sources(pilot_only=pilot_only):
        observation = observation_for_source(source)
        if dry_run:
            print(yaml.safe_dump(observation, sort_keys=False, allow_unicode=True))
        else:
            created.append(write_observation(observation))

    if not dry_run:
        for path in created:
            print(path.relative_to(ROOT))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="openva-observe")
    parser.add_argument("command", choices=["observe-all", "observe-pilot"])
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.command == "observe-all":
        return observe_sources(dry_run=args.dry_run, pilot_only=False)
    if args.command == "observe-pilot":
        return observe_sources(dry_run=args.dry_run, pilot_only=True)

    raise AssertionError("unreachable")


if __name__ == "__main__":
    raise SystemExit(main())
