import subprocess
from pathlib import Path

from tools.openva.repository_hygiene import branch_name_violations, scan_text


def tracked_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        text=True,
        capture_output=True,
        check=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def test_gitignore_covers_local_generated_artifacts():
    text = Path(".gitignore").read_text(encoding="utf-8")

    for pattern in [
        "__pycache__/",
        "*.pyc",
        "*.pyo",
        ".pytest_cache/",
        "release-artifacts.json",
        "reports/",
    ]:
        assert pattern in text


def test_no_tracked_python_bytecode_files():
    forbidden = [path for path in tracked_files() if path.endswith((".pyc", ".pyo"))]

    assert forbidden == []


def test_no_tracked_pycache_paths():
    forbidden = [path for path in tracked_files() if "/__pycache__/" in path or path.startswith("__pycache__/")]
    assert forbidden == []


def hygiene_codes(text: str) -> set[str]:
    return {item.code for item in scan_text(text, location="fixture")}


def test_repository_hygiene_flags_model_coauthor_attribution():
    trailer = "Co-" + "Authored-By: " + "Claude <noreply@example.invalid>"
    assert "model_coauthor_attribution" in hygiene_codes(trailer)


def test_repository_hygiene_flags_model_generation_attribution():
    sentence = "This document was " + "generated with ChatGPT."
    assert "model_generation_attribution" in hygiene_codes(sentence)


def test_repository_hygiene_flags_shared_conversation_url():
    url = "https://" + "chatgpt.com/share/example"
    assert "shared_conversation_url" in hygiene_codes(url)


def test_repository_hygiene_flags_model_session_reference():
    sentence = "See the " + "Codex session for implementation notes."
    assert "model_session_reference" in hygiene_codes(sentence)


def test_repository_hygiene_allows_legitimate_catalog_and_agent_language():
    text = """
    OpenAI and Anthropic are catalog vendors.
    OpenVA publishes agent exports and an MCP server.
    Generated by tools.openva.validate build-indexes.
    """
    assert scan_text(text, location="fixture") == []


def test_repository_hygiene_rejects_tool_branded_working_branch_names():
    assert branch_name_violations("codex/repository-cleanup")
    assert branch_name_violations("refs/heads/claude/catalog-fix")
    assert branch_name_violations("cursor/refactor")


def test_repository_hygiene_allows_neutral_branch_names():
    assert branch_name_violations("maintenance/repository-hygiene") == []
    assert branch_name_violations("catalog/openai-source-update") == []
    assert branch_name_violations("main") == []
